# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.srcs/sources_1/ip/SysClkWizard/SysClkWizard.xci
# IP: The module: 'SysClkWizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/SysClkWizard/SysClkWizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SysClkWizard'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/SysClkWizard/SysClkWizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'SysClkWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/SysClkWizard/SysClkWizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SysClkWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.srcs/sources_1/ip/SysClkWizard/SysClkWizard.xci
# IP: The module: 'SysClkWizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/SysClkWizard/SysClkWizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SysClkWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/SysClkWizard/SysClkWizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'SysClkWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/SysClkWizard/SysClkWizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SysClkWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
