# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.srcs/sources_1/ip/GPREG_IP/GPREG_IP.xci
# IP: The module: 'GPREG_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/GPREG_IP/GPREG_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPREG_IP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.srcs/sources_1/ip/GPREG_IP/GPREG_IP.xci
# IP: The module: 'GPREG_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/GPREG_IP/GPREG_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPREG_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
