# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.srcs/sources_1/ip/Program_BRAM/Program_BRAM.xci
# IP: The module: 'Program_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/Program_BRAM/Program_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Program_BRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.srcs/sources_1/ip/Program_BRAM/Program_BRAM.xci
# IP: The module: 'Program_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Diplomarbeit/HTMega/HTMega_FPGA/HTMega_FPGA.gen/sources_1/ip/Program_BRAM/Program_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Program_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
